# Generated by Django 5.1.15 on 2026-05-26 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_id', models.CharField(db_index=True, max_length=20)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_blocked', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contacttag')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'phone_number'], name='contacts_co_organiz_3aacf1_idx')],
                'unique_together': {('organization', 'wa_id')},
            },
        ),
    ]
