# Generated by Django 5.1.15 on 2026-05-26 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='fr', max_length=10)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('fallback_text', models.JSONField(default=dict, help_text='{"fr": "Je n\'ai pas compris", "en": "I did not understand"}')),
                ('max_invalid_retries', models.PositiveSmallIntegerField(default=3)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BotStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('message', 'Message'), ('menu', 'Menu'), ('condition', 'Condition'), ('api_call', 'API Call'), ('ai', 'AI'), ('payment', 'Payment'), ('assign_agent', 'Assign Agent'), ('end', 'End')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('next_step_key', models.CharField(blank=True, max_length=100)),
                ('translations', models.JSONField(default=dict)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('is_entry', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bots.botflow')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('flow', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step_key', models.CharField(max_length=100)),
                ('context_variables', models.JSONField(default=dict)),
                ('invalid_input_count', models.PositiveSmallIntegerField(default=0)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='contacts.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='conversations.conversation')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bots.botflow')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'contact', 'is_active'], name='bots_sessio_organiz_543a98_idx')],
            },
        ),
    ]
